In [1]:
import numpy as np

# Define 4 patterns (4-dimensional bipolar vectors)
patterns = np.array([
    [1, -1, 1, -1],
    [1, 1, -1, -1],
    [-1, -1, 1, 1],
    [1, 1, 1, 1]
])

# Initialize weight matrix
weights = np.zeros((4, 4))

# Train the network using Hebbian learning rule
for p in patterns:
    weights += np.outer(p, p)

# Remove self-connections
np.fill_diagonal(weights, 0)

def update(state, weights):
    prev_state = np.zeros_like(state)
    while not np.array_equal(state, prev_state):
        prev_state = state.copy()
        for i in range(len(state)):
            raw_input = np.dot(weights[i], state)
            state[i] = 1 if raw_input >= 0 else -1
    return state

if __name__ == "__main__":
    print("Stored patterns:")
    for p in patterns:
        print(p)

    # Test with a noisy version of the first pattern
    test_pattern = np.array([1, -1, -1, -1])  # flipped one bit
    print("\nTest pattern (noisy):")
    print(test_pattern)

    recovered = update(test_pattern.copy(), weights)
    print("\nRecovered pattern after convergence:")
    print(recovered)


Stored patterns:
[ 1 -1  1 -1]
[ 1  1 -1 -1]
[-1 -1  1  1]
[1 1 1 1]

Test pattern (noisy):
[ 1 -1 -1 -1]

Recovered pattern after convergence:
[ 1  1 -1 -1]
